src/java/com/leonardo/model/Allenatore.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leonardo.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Leonardo
 */
@Entity
@Table(name = "ALLENATORE")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Allenatore.findAll", query = "SELECT a FROM Allenatore a"),
    @NamedQuery(name = "Allenatore.findById", query = "SELECT a FROM Allenatore a WHERE a.id = :id"),
    @NamedQuery(name = "Allenatore.findByNome", query = "SELECT a FROM Allenatore a WHERE a.nome = :nome"),
    @NamedQuery(name = "Allenatore.findByCognome", query = "SELECT a FROM Allenatore a WHERE a.cognome = :cognome"),
    @NamedQuery(name = "Allenatore.findByGiocatore", query = "SELECT a FROM Allenatore a WHERE a.giocatore = :giocatore"),
    @NamedQuery(name = "Allenatore.findByNazionalita", query = "SELECT a FROM Allenatore a WHERE a.nazionalita = :nazionalita")})
public class Allenatore implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID")
    private Integer id;
    @Size(max = 45)
    @Column(name = "NOME")
    private String nome;
    @Size(max = 45)
    @Column(name = "COGNOME")
    private String cognome;
    @Column(name = "GIOCATORE")
    private Boolean giocatore;
    @Size(max = 45)
    @Column(name = "NAZIONALITA")
    private String nazionalita;
    @JoinColumn(name = "CAMPIONATO", referencedColumnName = "NOME")
    @ManyToOne
    private Campionato campionato;

    public Allenatore() {
    }

    public Allenatore(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public Boolean getGiocatore() {
        return giocatore;
    }

    public void setGiocatore(Boolean giocatore) {
        this.giocatore = giocatore;
    }

    public String getNazionalita() {
        return nazionalita;
    }

    public void setNazionalita(String nazionalita) {
        this.nazionalita = nazionalita;
    }

    public Campionato getCampionato() {
        return campionato;
    }

    public void setCampionato(Campionato campionato) {
        this.campionato = campionato;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Allenatore)) {
            return false;
        }
        Allenatore other = (Allenatore) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.leonardo.model.Allenatore[ id=" + id + " ]";
    }
    
}

src/java/com/leonardo/model/util/PaginationHelper.java
package com.leonardo.model.util;

import javax.faces.model.DataModel;

public abstract class PaginationHelper {

    private int pageSize;
    private int page;

    public PaginationHelper(int pageSize) {
        this.pageSize = pageSize;
    }

    public abstract int getItemsCount();

    public abstract DataModel createPageDataModel();

    public int getPageFirstItem() {
        return page * pageSize;
    }

    public int getPageLastItem() {
        int i = getPageFirstItem() + pageSize - 1;
        int count = getItemsCount() - 1;
        if (i > count) {
            i = count;
        }
        if (i < 0) {
            i = 0;
        }
        return i;
    }

    public boolean isHasNextPage() {
        return (page + 1) * pageSize + 1 <= getItemsCount();
    }

    public void nextPage() {
        if (isHasNextPage()) {
            page++;
        }
    }

    public boolean isHasPreviousPage() {
        return page > 0;
    }

    public void previousPage() {
        if (isHasPreviousPage()) {
            page--;
        }
    }

    public int getPageSize() {
        return pageSize;
    }

}

src/java/com/leonardo/controller/AllenatoreController.java
package com.leonardo.controller;

import com.leonardo.model.Allenatore;
import com.leonardo.DAO.AllenatoreFacade;
import com.leonardo.model.util.JsfUtil;
import com.leonardo.model.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("allenatoreController")
@SessionScoped
public class AllenatoreController implements Serializable {

    private Allenatore current;
    private DataModel items = null;
    @EJB
    private com.leonardo.DAO.AllenatoreFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public AllenatoreController() {
    }

    public Allenatore getSelected() {
        if (current == null) {
            current = new Allenatore();
            selectedItemIndex = -1;
        }
        return current;
    }

    private AllenatoreFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Allenatore) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Allenatore();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AllenatoreCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Allenatore) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AllenatoreUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Allenatore) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AllenatoreDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            
            selectedItemIndex = count - 1;
            
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Allenatore getAllenatore(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Allenatore.class)
    public static class AllenatoreControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AllenatoreController controller = (AllenatoreController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "allenatoreController");
            return controller.getAllenatore(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Allenatore) {
                Allenatore o = (Allenatore) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Allenatore.class.getName());
            }
        }

    }

}

web/allenatore/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAllenatoreTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAllenatoreLabel_nome}" for="nome" />
                    <h:inputText id="nome" value="#{allenatoreController.selected.nome}" title="#{bundle.CreateAllenatoreTitle_nome}" />
                    <h:outputLabel value="#{bundle.CreateAllenatoreLabel_cognome}" for="cognome" />
                    <h:inputText id="cognome" value="#{allenatoreController.selected.cognome}" title="#{bundle.CreateAllenatoreTitle_cognome}" />
                    <h:outputLabel value="#{bundle.CreateAllenatoreLabel_giocatore}" for="giocatore" />
                    <h:selectBooleanCheckbox id="giocatore" value="#{allenatoreController.selected.giocatore}" title="#{bundle.CreateAllenatoreTitle_giocatore}" />
                    
                    <h:outputLabel value="#{bundle.CreateAllenatoreLabel_nazionalita}" for="nazionalita" />
                    <h:inputText id="nazionalita" value="#{allenatoreController.selected.nazionalita}" title="#{bundle.CreateAllenatoreTitle_nazionalita}" />
                    <h:outputLabel value="#{bundle.CreateAllenatoreLabel_campionato}" for="campionato" />
                    <h:selectOneMenu id="campionato" value="#{allenatoreController.selected.campionato}" title="#{bundle.CreateAllenatoreTitle_campionato}" >
                        <f:selectItems value="#{campionatoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{allenatoreController.create}" value="#{bundle.CreateAllenatoreSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{allenatoreController.prepareList}" value="#{bundle.CreateAllenatoreShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAllenatoreIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/allenatore/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAllenatoreTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_id}" for="id" />
                    <h:inputText id="id" value="#{allenatoreController.selected.id}" title="#{bundle.EditAllenatoreTitle_id}" required="true" requiredMessage="#{bundle.EditAllenatoreRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_nome}" for="nome" />
                    <h:inputText id="nome" value="#{allenatoreController.selected.nome}" title="#{bundle.EditAllenatoreTitle_nome}" />
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_cognome}" for="cognome" />
                    <h:inputText id="cognome" value="#{allenatoreController.selected.cognome}" title="#{bundle.EditAllenatoreTitle_cognome}" />
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_giocatore}" for="giocatore" />
                    <h:inputText id="giocatore" value="#{allenatoreController.selected.giocatore}" title="#{bundle.EditAllenatoreTitle_giocatore}" />
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_nazionalita}" for="nazionalita" />
                    <h:inputText id="nazionalita" value="#{allenatoreController.selected.nazionalita}" title="#{bundle.EditAllenatoreTitle_nazionalita}" />
                    <h:outputLabel value="#{bundle.EditAllenatoreLabel_campionato}" for="campionato" />
                    <h:selectOneMenu id="campionato" value="#{allenatoreController.selected.campionato}" title="#{bundle.EditAllenatoreTitle_campionato}" >
                        <f:selectItems value="#{campionatoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{allenatoreController.update}" value="#{bundle.EditAllenatoreSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAllenatoreViewLink}"/>
                <br />
                <h:commandLink action="#{allenatoreController.prepareList}" value="#{bundle.EditAllenatoreShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAllenatoreIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/allenatore/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAllenatoreTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAllenatoreEmpty}" rendered="#{allenatoreController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{allenatoreController.items.rowCount > 0}">
                    <h:outputText value="#{allenatoreController.pagination.pageFirstItem + 1}..#{allenatoreController.pagination.pageLastItem + 1}/#{allenatoreController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{allenatoreController.previous}" value="#{bundle.Previous} #{allenatoreController.pagination.pageSize}" rendered="#{allenatoreController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{allenatoreController.next}" value="#{bundle.Next} #{allenatoreController.pagination.pageSize}" rendered="#{allenatoreController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{allenatoreController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_nome}"/>
                            </f:facet>
                            <h:outputText value="#{item.nome}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_cognome}"/>
                            </f:facet>
                            <h:outputText value="#{item.cognome}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_giocatore}"/>
                            </f:facet>
                            <h:outputText value="#{item.giocatore}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_nazionalita}"/>
                            </f:facet>
                            <h:outputText value="#{item.nazionalita}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAllenatoreTitle_campionato}"/>
                            </f:facet>
                            <h:outputText value="#{item.campionato}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{allenatoreController.prepareView}" value="#{bundle.ListAllenatoreViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{allenatoreController.prepareEdit}" value="#{bundle.ListAllenatoreEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{allenatoreController.destroy}" value="#{bundle.ListAllenatoreDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{allenatoreController.prepareCreate}" value="#{bundle.ListAllenatoreCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAllenatoreIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/allenatore/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAllenatoreTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_id}"/>
                    <h:outputText value="#{allenatoreController.selected.id}" title="#{bundle.ViewAllenatoreTitle_id}"/>
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_nome}"/>
                    <h:outputText value="#{allenatoreController.selected.nome}" title="#{bundle.ViewAllenatoreTitle_nome}"/>
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_cognome}"/>
                    <h:outputText value="#{allenatoreController.selected.cognome}" title="#{bundle.ViewAllenatoreTitle_cognome}"/>
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_giocatore}"/>
                    <h:outputText value="#{allenatoreController.selected.giocatore}" title="#{bundle.ViewAllenatoreTitle_giocatore}"/>
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_nazionalita}"/>
                    <h:outputText value="#{allenatoreController.selected.nazionalita}" title="#{bundle.ViewAllenatoreTitle_nazionalita}"/>
                    <h:outputText value="#{bundle.ViewAllenatoreLabel_campionato}"/>
                    <h:outputText value="#{allenatoreController.selected.campionato}" title="#{bundle.ViewAllenatoreTitle_campionato}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{allenatoreController.destroyAndView}" value="#{bundle.ViewAllenatoreDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAllenatoreEditLink}"/>
                <br />
                <h:commandLink action="#{allenatoreController.prepareCreate}" value="#{bundle.ViewAllenatoreCreateLink}" />
                <br />
                <h:commandLink action="#{allenatoreController.prepareList}" value="#{bundle.ViewAllenatoreShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAllenatoreIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>